backend:
  name: git-gateway       # Netlify: zet Identity + Git Gateway aan
  branch: main

media_folder: "public/uploads"   # waar bestanden in de repo staan
public_folder: "/uploads"        # hoe de app ze benadert (URL)

local_backend: true

collections:
  - name: "home"
    label: "Homepage"
    delete: false
    format: "json"
    editor: { preview: false }
    files:
      - file: "src/content/home.json"
        label: "Homepage content"
        name: "home_json"
        fields:
          - { label: "Hero titel", name: "heroTitle", widget: "string" }
          - { label: "Hero ondertitel", name: "heroSubtitle", widget: "text" }
          - { label: "Hero afbeelding", name: "heroImage", widget: "image", allow_multiple: false, media_folder: "public/uploads", public_folder: "/uploads" }
          - label: "CTA's"
            name: "ctas"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Pad (route)", name: "to", widget: "string" }
              - { label: "Variant", name: "variant", widget: "select", options: ["primary", "secondary"] }
          - label: "Badges"
            name: "badges"
            widget: "list"
            field: { label: "Tekst", name: "text", widget: "string" }
          - label: "Stappen"
            name: "steps"
            widget: "list"
            fields:
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "text", widget: "text" }
          - label: "Waarom FitFi"
            name: "reasons"
            widget: "list"
            field: { label: "Punt", name: "text", widget: "string" }
          - label: "FAQ"
            name: "faq"
            widget: "list"
            fields:
              - { label: "Vraag", name: "q", widget: "string" }
              - { label: "Antwoord", name: "a", widget: "text" }