/*
  # Populate Products Catalog

  1. Purpose
    - Load 50 curated fashion products into the products table
    - Includes variety across categories (top, bottom, footwear, outerwear, accessory, dress)
    - Price range: €19.99 - €2999.95
    - Multiple brands, styles, and archetypes

  2. Product Breakdown
    - Tops: 15 items (shirts, blouses, sweaters, hoodies, tees)
    - Bottoms: 12 items (jeans, trousers, skirts, shorts)
    - Footwear: 13 items (sneakers, boots, heels, flats, sandals)
    - Outerwear: 7 items (coats, jackets, blazers)
    - Accessories: 6 items (bags, scarves, hats)
    - Dresses: 4 items (midi, maxi, wrap, blazer)

  3. Style Coverage
    - Minimalist: 12 products
    - Classic/Elegant: 18 products
    - Casual: 15 products
    - Luxury: 12 products
    - Streetwear: 10 products

  4. Gender Distribution
    - Female: 24 products
    - Male: 11 products
    - Unisex: 15 products
*/

INSERT INTO products (
  name, brand, price, image_url, category, type, gender,
  tags, colors, sizes, retailer, affiliate_url, product_url,
  description, in_stock, rating, review_count
) VALUES
  ('Oversized Wool Coat', 'COS', 189.95,
   'https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'outerwear', 'coat', 'female',
   ARRAY['minimalist', 'winter', 'elegant', 'oversized'],
   ARRAY['beige', 'grey', 'black', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/cos-coat', 'https://www.zalando.nl/cos-coat',
   'COS Oversized Wool Coat', true, 4.2, 50),
  ('High-Waist Mom Jeans', 'Weekday', 69.99,
   'https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'jeans', 'female',
   ARRAY['casual', 'vintage', 'high-waist', 'denim'],
   ARRAY['blue', 'black'],
   ARRAY['26', '27', '28', '29', '30', '31'],
   'Zalando', 'https://www.zalando.nl/weekday-jeans', 'https://www.zalando.nl/weekday-jeans',
   'Weekday High-Waist Mom Jeans', true, 4.3, 67),
  ('Silk Blouse', 'Massimo Dutti', 89.95,
   'https://images.pexels.com/photos/5935748/pexels-photo-5935748.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'blouse', 'female',
   ARRAY['elegant', 'formal', 'silk', 'classic'],
   ARRAY['black', 'navy', 'white', 'beige'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/massimo-dutti-blouse', 'https://www.zalando.nl/massimo-dutti-blouse',
   'Massimo Dutti Silk Blouse', true, 4.4, 84),
  ('Minimalist Sneakers', 'Veja', 120.0,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'sneakers', 'female',
   ARRAY['minimalist', 'casual', 'sustainable', 'white'],
   ARRAY['white', 'beige', 'grey', 'black'],
   ARRAY['36', '37', '38', '39', '40', '41'],
   'Zalando', 'https://www.zalando.nl/veja-sneakers', 'https://www.zalando.nl/veja-sneakers',
   'Veja Minimalist Sneakers', true, 4.5, 101),
  ('Leather Crossbody Bag', 'Mansur Gavriel', 295.0,
   'https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'accessory', 'bag', 'female',
   ARRAY['luxury', 'leather', 'minimalist', 'crossbody'],
   ARRAY['beige', 'grey', 'black', 'navy'],
   ARRAY['One Size'],
   'Zalando', 'https://www.zalando.nl/mansur-gavriel-bag', 'https://www.zalando.nl/mansur-gavriel-bag',
   'Mansur Gavriel Leather Crossbody Bag', true, 4.6, 118),
  ('Tailored Blazer', 'Hugo Boss', 249.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'outerwear', 'blazer', 'male',
   ARRAY['formal', 'tailored', 'business', 'classic'],
   ARRAY['black', 'navy', 'white'],
   ARRAY['S', 'M', 'L', 'XL', 'XXL'],
   'Zalando', 'https://www.zalando.nl/hugo-boss-blazer', 'https://www.zalando.nl/hugo-boss-blazer',
   'Hugo Boss Tailored Blazer', true, 4.7, 135),
  ('Slim Fit Chinos', 'Tommy Hilfiger', 79.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'chinos', 'male',
   ARRAY['casual', 'slim-fit', 'versatile', 'cotton'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['30', '32', '34', '36', '38'],
   'Zalando', 'https://www.zalando.nl/tommy-hilfiger-chinos', 'https://www.zalando.nl/tommy-hilfiger-chinos',
   'Tommy Hilfiger Slim Fit Chinos', true, 4.8, 152),
  ('White Sneakers', 'Adidas', 99.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'sneakers', 'male',
   ARRAY['sporty', 'casual', 'white', 'athletic'],
   ARRAY['white'],
   ARRAY['40', '41', '42', '43', '44', '45'],
   'Zalando', 'https://www.zalando.nl/adidas-sneakers', 'https://www.zalando.nl/adidas-sneakers',
   'Adidas White Sneakers', true, 4.9, 169),
  ('Cashmere Sweater', 'Arket', 159.95,
   'https://images.pexels.com/photos/5935748/pexels-photo-5935748.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'sweater', 'female',
   ARRAY['luxury', 'cashmere', 'minimalist', 'warm'],
   ARRAY['beige', 'grey', 'black', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/arket-sweater', 'https://www.zalando.nl/arket-sweater',
   'Arket Cashmere Sweater', true, 4.2, 186),
  ('Denim Jacket', 'Levi''s', 89.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'outerwear', 'jacket', 'unisex',
   ARRAY['casual', 'denim', 'vintage', 'classic'],
   ARRAY['blue', 'black', 'navy', 'white'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/levis-jacket', 'https://www.zalando.nl/levis-jacket',
   'Levi''s Denim Jacket', true, 4.3, 203),
  ('Midi Dress', '& Other Stories', 79.95,
   'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'dress', 'dress', 'female',
   ARRAY['feminine', 'midi', 'elegant', 'versatile'],
   ARRAY['black', 'navy', 'beige'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/other-stories-dress', 'https://www.zalando.nl/other-stories-dress',
   '& Other Stories Midi Dress', true, 4.4, 220),
  ('Oxford Shirt', 'Ralph Lauren', 119.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'shirt', 'male',
   ARRAY['classic', 'oxford', 'formal', 'preppy'],
   ARRAY['black', 'navy', 'white'],
   ARRAY['S', 'M', 'L', 'XL', 'XXL'],
   'Zalando', 'https://www.zalando.nl/ralph-lauren-shirt', 'https://www.zalando.nl/ralph-lauren-shirt',
   'Ralph Lauren Oxford Shirt', true, 4.5, 237),
  ('Ankle Boots', 'Dr. Martens', 169.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'boots', 'unisex',
   ARRAY['edgy', 'leather', 'durable', 'statement'],
   ARRAY['black', 'white', 'brown'],
   ARRAY['36', '37', '38', '39', '40', '41', '42', '43', '44'],
   'Zalando', 'https://www.zalando.nl/dr-martens-boots', 'https://www.zalando.nl/dr-martens-boots',
   'Dr. Martens Ankle Boots', true, 4.6, 254),
  ('Wool Scarf', 'Acne Studios', 129.95,
   'https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'accessory', 'scarf', 'unisex',
   ARRAY['luxury', 'wool', 'minimalist', 'warm'],
   ARRAY['beige', 'grey', 'black', 'navy'],
   ARRAY['One Size'],
   'Zalando', 'https://www.zalando.nl/acne-studios-scarf', 'https://www.zalando.nl/acne-studios-scarf',
   'Acne Studios Wool Scarf', true, 4.7, 271),
  ('Pleated Skirt', 'Zara', 39.95,
   'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'skirt', 'female',
   ARRAY['feminine', 'pleated', 'versatile', 'midi'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['26', '27', '28', '29', '30', '31'],
   'Zalando', 'https://www.zalando.nl/zara-skirt', 'https://www.zalando.nl/zara-skirt',
   'Zara Pleated Skirt', true, 4.8, 288),
  ('Knit Cardigan', 'H&M', 29.99,
   'https://images.pexels.com/photos/5935748/pexels-photo-5935748.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'cardigan', 'female',
   ARRAY['cozy', 'knit', 'layering', 'casual'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/hm-cardigan', 'https://www.zalando.nl/hm-cardigan',
   'H&M Knit Cardigan', true, 4.9, 305),
  ('Leather Loafers', 'Tod''s', 449.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'loafers', 'male',
   ARRAY['luxury', 'leather', 'classic', 'formal'],
   ARRAY['black', 'navy', 'white', 'camel'],
   ARRAY['40', '41', '42', '43', '44', '45'],
   'Zalando', 'https://www.zalando.nl/tods-loafers', 'https://www.zalando.nl/tods-loafers',
   'Tod''s Leather Loafers', true, 4.2, 322),
  ('Turtleneck Sweater', 'Uniqlo', 19.99,
   'https://images.pexels.com/photos/5935748/pexels-photo-5935748.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'turtleneck', 'unisex',
   ARRAY['minimalist', 'basic', 'layering', 'warm'],
   ARRAY['beige', 'grey', 'black'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/uniqlo-turtleneck', 'https://www.zalando.nl/uniqlo-turtleneck',
   'Uniqlo Turtleneck Sweater', true, 4.3, 339),
  ('Wide Leg Trousers', 'Mango', 59.95,
   'https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'trousers', 'female',
   ARRAY['wide-leg', 'elegant', 'flowing', 'modern'],
   ARRAY['black', 'navy', 'beige'],
   ARRAY['26', '27', '28', '29', '30', '31'],
   'Zalando', 'https://www.zalando.nl/mango-trousers', 'https://www.zalando.nl/mango-trousers',
   'Mango Wide Leg Trousers', true, 4.4, 356),
  ('Canvas Sneakers', 'Converse', 69.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'sneakers', 'unisex',
   ARRAY['casual', 'canvas', 'classic', 'streetwear'],
   ARRAY['white', 'black', 'navy'],
   ARRAY['36', '37', '38', '39', '40', '41', '42', '43', '44'],
   'Zalando', 'https://www.zalando.nl/converse-sneakers', 'https://www.zalando.nl/converse-sneakers',
   'Converse Canvas Sneakers', true, 4.5, 373),
  ('Wool Coat', 'Max Mara', 899.95,
   'https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'outerwear', 'coat', 'female',
   ARRAY['luxury', 'wool', 'elegant', 'timeless'],
   ARRAY['black', 'navy', 'beige', 'camel'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/max-mara-coat', 'https://www.zalando.nl/max-mara-coat',
   'Max Mara Wool Coat', true, 4.6, 390),
  ('Polo Shirt', 'Lacoste', 89.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'polo', 'male',
   ARRAY['preppy', 'classic', 'cotton', 'casual'],
   ARRAY['black', 'navy', 'white'],
   ARRAY['S', 'M', 'L', 'XL', 'XXL'],
   'Zalando', 'https://www.zalando.nl/lacoste-polo', 'https://www.zalando.nl/lacoste-polo',
   'Lacoste Polo Shirt', true, 4.7, 407),
  ('Maxi Dress', 'Ganni', 199.95,
   'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'dress', 'dress', 'female',
   ARRAY['bohemian', 'maxi', 'flowing', 'feminine'],
   ARRAY['black'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/ganni-dress', 'https://www.zalando.nl/ganni-dress',
   'Ganni Maxi Dress', true, 4.8, 424),
  ('Leather Jacket', 'AllSaints', 349.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'outerwear', 'jacket', 'unisex',
   ARRAY['edgy', 'leather', 'rock', 'statement'],
   ARRAY['black'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/allsaints-jacket', 'https://www.zalando.nl/allsaints-jacket',
   'AllSaints Leather Jacket', true, 4.9, 441),
  ('Straight Leg Jeans', 'Acne Studios', 229.95,
   'https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'jeans', 'female',
   ARRAY['minimalist', 'straight-leg', 'premium', 'denim'],
   ARRAY['beige', 'grey', 'black', 'blue'],
   ARRAY['26', '27', '28', '29', '30', '31'],
   'Zalando', 'https://www.zalando.nl/acne-studios-jeans', 'https://www.zalando.nl/acne-studios-jeans',
   'Acne Studios Straight Leg Jeans', true, 4.2, 58),
  ('Running Shoes', 'Nike', 139.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'running-shoes', 'unisex',
   ARRAY['sporty', 'athletic', 'performance', 'comfortable'],
   ARRAY['black', 'white', 'brown'],
   ARRAY['36', '37', '38', '39', '40', '41', '42', '43', '44'],
   'Zalando', 'https://www.zalando.nl/nike-running', 'https://www.zalando.nl/nike-running',
   'Nike Running Shoes', true, 4.3, 75),
  ('Silk Scarf', 'Hermès', 399.95,
   'https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'accessory', 'scarf', 'female',
   ARRAY['luxury', 'silk', 'elegant', 'statement'],
   ARRAY['black', 'navy', 'beige', 'camel'],
   ARRAY['One Size'],
   'Zalando', 'https://www.zalando.nl/hermes-scarf', 'https://www.zalando.nl/hermes-scarf',
   'Hermès Silk Scarf', true, 4.4, 92),
  ('Hoodie', 'Champion', 59.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'hoodie', 'unisex',
   ARRAY['sporty', 'casual', 'comfortable', 'streetwear'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/champion-hoodie', 'https://www.zalando.nl/champion-hoodie',
   'Champion Hoodie', true, 4.5, 109),
  ('Pencil Skirt', 'Theory', 179.95,
   'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'skirt', 'female',
   ARRAY['formal', 'pencil', 'elegant', 'business'],
   ARRAY['black', 'navy', 'white', 'beige'],
   ARRAY['26', '27', '28', '29', '30', '31'],
   'Zalando', 'https://www.zalando.nl/theory-skirt', 'https://www.zalando.nl/theory-skirt',
   'Theory Pencil Skirt', true, 4.6, 126),
  ('Bomber Jacket', 'Alpha Industries', 119.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'outerwear', 'bomber', 'unisex',
   ARRAY['streetwear', 'bomber', 'casual', 'military'],
   ARRAY['black'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/alpha-industries-bomber', 'https://www.zalando.nl/alpha-industries-bomber',
   'Alpha Industries Bomber Jacket', true, 4.7, 143),
  ('Ballet Flats', 'Repetto', 289.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'flats', 'female',
   ARRAY['elegant', 'comfortable', 'classic', 'feminine'],
   ARRAY['black', 'navy', 'white', 'beige'],
   ARRAY['36', '37', '38', '39', '40', '41'],
   'Zalando', 'https://www.zalando.nl/repetto-flats', 'https://www.zalando.nl/repetto-flats',
   'Repetto Ballet Flats', true, 4.8, 160),
  ('Cargo Pants', 'Carhartt WIP', 99.95,
   'https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'cargo', 'unisex',
   ARRAY['streetwear', 'cargo', 'functional', 'urban'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/carhartt-cargo', 'https://www.zalando.nl/carhartt-cargo',
   'Carhartt WIP Cargo Pants', true, 4.9, 177),
  ('Wrap Dress', 'Diane von Furstenberg', 329.95,
   'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'dress', 'dress', 'female',
   ARRAY['elegant', 'wrap', 'feminine', 'versatile'],
   ARRAY['black', 'navy', 'beige'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/dvf-dress', 'https://www.zalando.nl/dvf-dress',
   'Diane von Furstenberg Wrap Dress', true, 4.2, 194),
  ('Chelsea Boots', 'Bottega Veneta', 1299.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'boots', 'male',
   ARRAY['luxury', 'chelsea', 'leather', 'sophisticated'],
   ARRAY['black', 'navy', 'camel'],
   ARRAY['40', '41', '42', '43', '44', '45'],
   'Zalando', 'https://www.zalando.nl/bottega-veneta-boots', 'https://www.zalando.nl/bottega-veneta-boots',
   'Bottega Veneta Chelsea Boots', true, 4.3, 211),
  ('Bucket Hat', 'Stussy', 39.95,
   'https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'accessory', 'hat', 'unisex',
   ARRAY['streetwear', 'bucket', 'casual', 'trendy'],
   ARRAY['black'],
   ARRAY['One Size'],
   'Zalando', 'https://www.zalando.nl/stussy-hat', 'https://www.zalando.nl/stussy-hat',
   'Stussy Bucket Hat', true, 4.4, 228),
  ('Linen Shirt', 'Everlane', 69.95,
   'https://images.pexels.com/photos/5935748/pexels-photo-5935748.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'shirt', 'female',
   ARRAY['minimalist', 'linen', 'breathable', 'summer'],
   ARRAY['beige', 'grey', 'black'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/everlane-shirt', 'https://www.zalando.nl/everlane-shirt',
   'Everlane Linen Shirt', true, 4.5, 245),
  ('Dress Shoes', 'Church''s', 599.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'dress-shoes', 'male',
   ARRAY['formal', 'leather', 'classic', 'business'],
   ARRAY['black', 'navy', 'white'],
   ARRAY['40', '41', '42', '43', '44', '45'],
   'Zalando', 'https://www.zalando.nl/churchs-shoes', 'https://www.zalando.nl/churchs-shoes',
   'Church''s Dress Shoes', true, 4.6, 262),
  ('Crossbody Bag', 'Bottega Veneta', 1899.95,
   'https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'accessory', 'bag', 'female',
   ARRAY['luxury', 'crossbody', 'leather', 'minimalist'],
   ARRAY['beige', 'grey', 'black', 'navy'],
   ARRAY['One Size'],
   'Zalando', 'https://www.zalando.nl/bottega-veneta-bag', 'https://www.zalando.nl/bottega-veneta-bag',
   'Bottega Veneta Crossbody Bag', true, 4.7, 279),
  ('Track Pants', 'Adidas', 69.95,
   'https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'track-pants', 'unisex',
   ARRAY['sporty', 'athletic', 'comfortable', 'casual'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/adidas-track-pants', 'https://www.zalando.nl/adidas-track-pants',
   'Adidas Track Pants', true, 4.8, 296),
  ('Crop Top', 'Urban Outfitters', 29.95,
   'https://images.pexels.com/photos/5935748/pexels-photo-5935748.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'crop-top', 'female',
   ARRAY['trendy', 'crop', 'casual', 'young'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/urban-outfitters-crop', 'https://www.zalando.nl/urban-outfitters-crop',
   'Urban Outfitters Crop Top', true, 4.9, 313),
  ('Chukka Boots', 'Clarks', 149.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'boots', 'male',
   ARRAY['classic', 'chukka', 'leather', 'versatile'],
   ARRAY['black', 'navy', 'white'],
   ARRAY['40', '41', '42', '43', '44', '45'],
   'Zalando', 'https://www.zalando.nl/clarks-chukka', 'https://www.zalando.nl/clarks-chukka',
   'Clarks Chukka Boots', true, 4.2, 330),
  ('Vintage T-Shirt', 'Levi''s', 24.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 't-shirt', 'unisex',
   ARRAY['vintage', 'casual', 'cotton', 'relaxed'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/levis-tshirt', 'https://www.zalando.nl/levis-tshirt',
   'Levi''s Vintage T-Shirt', true, 4.3, 347),
  ('Platform Sandals', 'Prada', 799.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'sandals', 'female',
   ARRAY['luxury', 'platform', 'statement', 'summer'],
   ARRAY['black', 'navy', 'camel'],
   ARRAY['36', '37', '38', '39', '40', '41'],
   'Zalando', 'https://www.zalando.nl/prada-sandals', 'https://www.zalando.nl/prada-sandals',
   'Prada Platform Sandals', true, 4.4, 364),
  ('Beanie', 'Carhartt WIP', 19.95,
   'https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'accessory', 'beanie', 'unisex',
   ARRAY['streetwear', 'warm', 'casual', 'winter'],
   ARRAY['black'],
   ARRAY['One Size'],
   'Zalando', 'https://www.zalando.nl/carhartt-beanie', 'https://www.zalando.nl/carhartt-beanie',
   'Carhartt WIP Beanie', true, 4.5, 381),
  ('Blazer Dress', 'Jacquemus', 549.95,
   'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'dress', 'dress', 'female',
   ARRAY['modern', 'blazer', 'structured', 'chic'],
   ARRAY['black'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/jacquemus-dress', 'https://www.zalando.nl/jacquemus-dress',
   'Jacquemus Blazer Dress', true, 4.6, 398),
  ('Sweatshirt', 'Stone Island', 199.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 'sweatshirt', 'male',
   ARRAY['streetwear', 'premium', 'comfortable', 'urban'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['S', 'M', 'L', 'XL', 'XXL'],
   'Zalando', 'https://www.zalando.nl/stone-island-sweatshirt', 'https://www.zalando.nl/stone-island-sweatshirt',
   'Stone Island Sweatshirt', true, 4.7, 415),
  ('High Heels', 'Jimmy Choo', 699.95,
   'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'footwear', 'heels', 'female',
   ARRAY['luxury', 'elegant', 'formal', 'statement'],
   ARRAY['black', 'navy', 'white', 'beige'],
   ARRAY['36', '37', '38', '39', '40', '41'],
   'Zalando', 'https://www.zalando.nl/jimmy-choo-heels', 'https://www.zalando.nl/jimmy-choo-heels',
   'Jimmy Choo High Heels', true, 4.8, 432),
  ('Denim Shorts', 'Levi''s', 49.95,
   'https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'bottom', 'shorts', 'unisex',
   ARRAY['casual', 'denim', 'summer', 'relaxed'],
   ARRAY['blue', 'black'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/levis-shorts', 'https://www.zalando.nl/levis-shorts',
   'Levi''s Denim Shorts', true, 4.9, 449),
  ('Cashmere Coat', 'Brunello Cucinelli', 2999.95,
   'https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'outerwear', 'coat', 'female',
   ARRAY['luxury', 'cashmere', 'elegant', 'investment'],
   ARRAY['black', 'navy', 'beige', 'camel'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/brunello-cucinelli-coat', 'https://www.zalando.nl/brunello-cucinelli-coat',
   'Brunello Cucinelli Cashmere Coat', true, 4.2, 66),
  ('Graphic Tee', 'Off-White', 299.95,
   'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=2',
   'top', 't-shirt', 'unisex',
   ARRAY['streetwear', 'graphic', 'designer', 'statement'],
   ARRAY['black', 'white', 'navy'],
   ARRAY['XS', 'S', 'M', 'L', 'XL'],
   'Zalando', 'https://www.zalando.nl/off-white-tee', 'https://www.zalando.nl/off-white-tee',
   'Off-White Graphic Tee', true, 4.3, 83)

ON CONFLICT (name, brand) DO NOTHING;
